// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class ServicioFooterBuenGobiernoTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void servicioFooterBuenGobierno() {
    // Test name: Servicio | Footer| Buen_Gobierno
    // Step # | name | target | value | comment
    // 1 | open | https://www.choucairtesting.com/servicio/ |  | 
    driver.get("https://www.choucairtesting.com/servicio/");
    // 2 | setWindowSize | 1292x768 |  | 
    driver.manage().window().setSize(new Dimension(1292, 768));
    // 3 | click | css=a:nth-child(3) > strong |  | 
    driver.findElement(By.cssSelector("a:nth-child(3) > strong")).click();
  }
}
