// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class ServicioMenuprincipalValidarbuscadordepalabrasclavesconresultadosresultadosTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void servicioMenuprincipalValidarbuscadordepalabrasclavesconresultadosresultados() {
    // Test name: Servicio | Menu_principal |Validar_buscador_de_palabras_claves_con_resultados_resultados
    // Step # | name | target | value | comment
    // 1 | open | https://www.choucairtesting.com/servicio/ |  | 
    driver.get("https://www.choucairtesting.com/servicio/");
    // 2 | setWindowSize | 1382x744 |  | 
    driver.manage().window().setSize(new Dimension(1382, 744));
    // 3 | mouseOver | css=.search-icon |  | 
    {
      WebElement element = driver.findElement(By.cssSelector(".search-icon"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 4 | click | css=.search-icon |  | 
    driver.findElement(By.cssSelector(".search-icon")).click();
    // 5 | mouseOut | css=.search-icon |  | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 6 | click | name=s |  | 
    driver.findElement(By.name("s")).click();
    // 7 | type | name=s | Industria | 
    driver.findElement(By.name("s")).sendKeys("Industria");
    // 8 | sendKeys | name=s | ${KEY_ENTER} | 
    driver.findElement(By.name("s")).sendKeys(Keys.ENTER);
  }
}
